project_id = "fdxyittddmpyhaiijddp"

[functions.telegram-auth]
verify_jwt = false

[functions.verify-channel]
verify_jwt = false

[functions.create-campaign]
verify_jwt = false

[functions.ton-price]
verify_jwt = false
