project_id = "fdxyittddmpyhaiijddp"

[functions.telegram-auth]
verify_jwt = false

[functions.verify-channel]
verify_jwt = false

[functions.create-campaign]
verify_jwt = false

[functions.ton-price]
verify_jwt = false

[functions.delete-campaign]
verify_jwt = false

[functions.send-campaign-preview]
verify_jwt = false

[functions.preview-channel]
verify_jwt = false

[functions.upload-campaign-media]
verify_jwt = false
