project_id = "fdxyittddmpyhaiijddp"

[functions.telegram-auth]
verify_jwt = false

[functions.verify-channel]
verify_jwt = false

[functions.create-campaign]
verify_jwt = false

[functions.ton-price]
verify_jwt = false

[functions.delete-campaign]
verify_jwt = false

[functions.send-campaign-preview]
verify_jwt = false

[functions.preview-channel]
verify_jwt = false

[functions.upload-campaign-media]
verify_jwt = false

[functions.update-channel-status]
verify_jwt = false

[functions.user-channels]
verify_jwt = false

[functions.channel-team]
verify_jwt = false

[functions.join-channel-as-admin]
verify_jwt = false

[functions.recheck-admin-status]
verify_jwt = false

[functions.refresh-channel-stats]
verify_jwt = false

[functions.save-wallet]
verify_jwt = false

[functions.create-deal]
verify_jwt = false

[functions.notify-deal-payment]
verify_jwt = false

[functions.check-escrow-payments]
verify_jwt = false
